### ISSUE TITLE
Requesting conda package for simplified installation

### ISSUE THREAD

**Issue by ekiefl** [minmarg/gtalign_alpha#1]
First of all, thanks for your hard work making this tool.

## Current Installation Process:

The current instructions involve several steps, including cloning the repository, running shell scripts or batch files, and ensuring specific software versions and compilers are installed. While this is manageable, it can be cumbersome, error-prone, and hinders gtalign being effectively built into other software/workflows.

## Benefits of a Conda Package:

- **Ease of Installation**: A simple `conda install gtalign` command could replace multiple steps in the current process.
- **Dependency Management**: Conda handles dependencies automatically, reducing the likelihood of version conflicts or missing packages.
- **Cross-Platform Support**: Conda works across Linux, macOS, and Windows, ensuring a consistent installation experience.
- **Environment Isolation**: Conda environments can isolate the installation, preventing potential conflicts with other software.
- **Adopted by Scientists**: Conda is widely used and expected by scientists

**Comment by minmarg** [comment]
Thank you for your valuable suggestion. I plan to revisit this point in a month or two.

**Comment by minmarg** [comment]
Conda packages are now available.
